### ISSUE TITLE
在主播未停止本次推流前录制的视频只有15帧，停止推流后会自动修复到60帧

### ISSUE THREAD

**Issue by chang147** [acgnhiki/blrec#1]
在主播未停止本次推流前录制的视频只有15帧，停止推流后会自动修复到60帧

**Comment by chang147** [comment]
是SRT推流，可否在分割视频后直接先修复视频，后续会考虑优化这点嘛？

**Comment by acgnhiki** [comment]
现在是录制结束才对全部文件进行处理的，也就是要等录制结束后录播文件才可用且没有问题，后续会考虑文件完成就马上进行处理。

**Comment by acgnhiki** [comment]
@chang147 
已经改好了 3e71c39，请更新到版本 v1.2.0 。 
现在分割了文件就马上对录制完成的文件进行处理了，但处理需要些时间。
在任务详情页可以看正在处理的文件的进度和录播文件的状态，文件的状态为 **已完成** 就是处理好了。
