### ISSUE TITLE
原始模式转码后的注释样式问题

### ISSUE THREAD

**Issue by InterestingFred** [acgnhiki/blrec#106]
原始模式转码后的注释样式问题
![图片](https://user-images.githubusercontent.com/106480847/182416876-721ee587-5d62-410c-957b-b767873a754c.png)
comment样式与flv转码不一致（虽然信息没缺）

**Comment by acgnhiki** [comment]
这里 VLC 显示的不是 Comment 而是 Description，用 ffprobe 看下就知道了。
