### ISSUE TITLE
能否在网络出现波动时在录播文件夹生成对应直播标题的报错提醒?

### ISSUE THREAD

**Issue by threewatermeter** [acgnhiki/blrec#11]
现在的情况是,如果出现了网络的临时中断,导致录播内容缺失,录制下来的文件是直接把两段视频连在一起,如果不亲自查看一遍整个视频或者通过其他渠道录制的文件进行长度的对比,很难发现内容有中断,不知道能不能在检测到有内容缺失的时候在文件名做出标注,或者是直接生成对应录播文件名的错误日志?

**Comment by acgnhiki** [comment]
流中断拼接详情记录在录播文件里了，可以先看一下 FAQ。 [怎么知道是否出现了流中断](https://github.com/acgnhiki/blrec/blob/master/FAQ.md#%E6%80%8E%E4%B9%88%E7%9F%A5%E9%81%93%E6%98%AF%E5%90%A6%E5%87%BA%E7%8E%B0%E4%BA%86%E6%B5%81%E4%B8%AD%E6%96%AD)

**Comment by threewatermeter** [comment]
看到了,非常感谢
