### ISSUE TITLE
[Feature request] 希望能自定义Bilibili 直播 API 的请求地址

### ISSUE THREAD

**Issue by baysonfox** [acgnhiki/blrec#112]
如题，可以通过更改请求地址来进行负载均衡或选择更好的直播服务器 (如 d1--cn-gotcha04.bilivideo.com)，使录制更加稳定.

**Comment by gitiray** [comment]
请问这种 gotcha 的地址是指 `直播流API主机地址` 吗？
`主站API` 和 `直播API` 又有什么可以选填的地址呢？

**Comment by Genteure** [comment]
> 请问这种 gotcha 的地址是指 直播流API主机地址 吗？

不是，这个是直播服务器的地址，参考： https://rec.danmuji.org/dev/bilibili-cdn/
