### ISSUE TITLE
主播网络波动导致内容丢失

### ISSUE THREAD

**Issue by eriri88888** [acgnhiki/blrec#113]
[blrec_2022-08-21-150038-281604.log](https://github.com/acgnhiki/blrec/files/9389558/blrec_2022-08-21-150038-281604.log)
21：22
21：29
21：31
主播网络波动。HLS流标准模式，每一段拼接后都会丢失3-5S左右的内容。我在同一台机子跑的录播姬虽然会出现内容重复，但是内容没缺失。

**Comment by acgnhiki** [comment]
主播推流出了问题服务器会重发缓存的数据，HLS 录制模式不会录制这些数据重复的片段。
