### ISSUE TITLE
[Feature request]希望能给是否连接弹幕服务器增加开关

### ISSUE THREAD

**Issue by KakaruHayate** [acgnhiki/blrec#114]
例如新华社（22015508）新华网（22102223）观察者网（948391）这些直播间很多时候是关闭弹幕和礼物功能的，这个时候是连接不到弹幕服务器的，会反复重连

**Comment by acgnhiki** [comment]
自动录制依赖弹幕服务器发送的事件，弹幕服务器必须连接。把弹幕接收超时去掉应该就不会反复重连了。
