### ISSUE TITLE
弹幕xml里的时间能不能再存一个易读的格式？

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [acgnhiki/blrec#119]
现在弹幕文件的 p 属性的第一个数字是时间，但是对着xml找录播文件相应片段时要先拿计算器算，很不方便，如果能再存一个计算好的时间就很方便了，比如存个成 1:23:44.5 这种格式

**Comment by acgnhiki** [comment]
potplayer 可以直接用弹幕的时间定位，不用自己计算。
