### ISSUE TITLE
有些主播直播中会改直播间标题，能否在后处理阶段把文件名改为最终的标题名

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [acgnhiki/blrec#120]
RT，有些主播中途会改直播间标题，目前blrec录制的文件名是开播时的标题名，但一般而言用户更想让文件名设置为最终的文件名，不知这个需求实现是否麻烦

**Comment by Georgebillion** [comment]
> 

尝试分段？分段可以解决部分问题，但如果要完整录播的话，那我貌似还不知道怎么弄

**Comment by acgnhiki** [comment]
> RT，有些主播中途会改直播间标题，目前blrec录制的文件名是开播时的标题名，但一般而言用户更想让文件名设置为最终的文件名，不知这个需求实现是否麻烦


把直播标题添加到文件名的目的是为了能看一眼文件名就知道直播内容吧？
但是有些主播会多次改直播内容和标题，那在文件名用最后的标题也没有多大意义。

**Comment by acgnhiki** [comment]
> > 
> 
> 尝试分段？分段可以解决部分问题，但如果要完整录播的话，那我貌似还不知道怎么弄

保存全部直播标题也许是更好的选择？
比如考虑把全部直播间标题单独保存在一个文件里。
也可以考虑把直播间标题作为章节名添加到 mp4 文件。

**Comment by Misaka-Mikoto-Tech** [comment]
> > > 
> > 
> > 
> > 尝试分段？分段可以解决部分问题，但如果要完整录播的话，那我貌似还不知道怎么弄
> 
> 保存全部直播标题也许是更好的选择？ 比如考虑把全部直播间标题单独保存在一个文件里。 也可以考虑把直播间标题作为章节名添加到 mp4 文件。

这个主意好
