### ISSUE TITLE
直播流读取超时是我本地网络问题吗

### ISSUE THREAD

**Issue by snfcx** [acgnhiki/blrec#128]
昨天录制的时候出现画面丢失，花屏重新拼接的情况，大概间隔了20-30s左右。
之前用录播机没有出现这样的情况，不知道是网络正好出问题了，还是数据读取超时这个设置要设置大一点？
这是日志文件，超时在03:35:02和09:04:27但是花屏重新拼接的片段和这两个时间对不上。
[blrec_2022-11-11-223101-174814.log](https://github.com/acgnhiki/blrec/files/9994317/blrec_2022-11-11-223101-174814.log)

**Comment by acgnhiki** [comment]
如果花屏不是出现在视频时间 03:15:52.007 这个位置那就是 CDN 的问题。

超时前 CDN 是 cn-zjjh-ct-04-09.bilivideo.com ，之后的是 xy117x29x81x113xy.mcdn.bilivideo.cn:486 。

2022-11-12 05:22:13,859 收到了新的 flv 头 tag, 服务器的流是拼接过的，可能缺数据或有问题。

现在国内 flv 流 CDN 大都有问题，可以考虑录制 hls 流或反代用国外的 CDN。
