### ISSUE TITLE
这是弹幕连接超时吧？

### ISSUE THREAD

**Issue by CloudyEagle** [acgnhiki/blrec#129]
![image](https://user-images.githubusercontent.com/58777085/202489520-d54d62a7-919f-4b81-91a0-f3c3ea2501d3.png)
这是继#86 安装后，也有跟着本项目更新到1.11.1后最近下午发生的问题。
不知道是怎么回事，听说是最近哔哩哔哩直播区的弹幕连接协议有点问题，
还是有其他的什么问题；我有试着排查是否是其他程序的问题，均没有发现。
感觉也不是自己的网络问题，因为早上7:30左右开机并开启此应用后，
用RDP监看到17:00前也没有问题啊，还是哔哩哔哩直播的风控嘞？
![image](https://user-images.githubusercontent.com/58777085/202492135-00511641-be5d-41e9-aee4-e3c5bb05c464.png)
不太可能是我的启动命令的问题吧！？

**Comment by acgnhiki** [comment]
弹幕接收设置了 30 秒的超时，这么多直播间都接收弹幕超时，可能是小破站的弹幕服务器又抽风了吧。。。
