### ISSUE TITLE
能否绑定本机的端口号

### ISSUE THREAD

**Issue by CloudyEagle** [acgnhiki/blrec#130]
请问可否尝试直接绑定本机端口，个人认为填0.0.0.0受限于IPv4协议的访问端口。
感觉这样做除了分配了内网IPv4的内网访问，有些高级路由器分配内网的IPv6后，
应该也能以IPv6的地址加端口号访问blrec吧。甚至在有些高级的网管路由里配置好相关IPv6的设置，还可能能在公网访问blrec。
曾经看到有人在配置文件里尝试过配置成IPv6，好像还能正常启动起来使用的样子。
![image](https://user-images.githubusercontent.com/58777085/202604671-888cce91-4da1-4cb2-a33c-52bae74a558f.png) ![QQ图片20221118092620](https://user-images.githubusercontent.com/58777085/202603867-83e42423-713b-4c9b-beaf-f3b3648943f7.png)

**Comment by sihuan** [comment]
默认情况下 blrec 默认绑定 host 0.0.0.0 ,端口 2233. 如果要自定义 host 和 port 可以分别用 `--host` 与 `--port` 选项修改，注意手动指定时需要同时指定 host 和 port.

**Comment by CloudyEagle** [comment]
我表达能力有限，再说明一下——
不受限于IPv4的本机端口绑定，而是直接绑定一整台设备的端口号；
只要被分配了地址，不管是IPv4还是IPv6在内网任何设备应该都可以访问，唯一需要的操作就是防火墙端口放行。
我这还是没有图，抽空弄张图上来。

**Comment by acgnhiki** [comment]
fastapi 默认用的是 uvicorn， [uvicorn 不支持多绑定](https://www.uvicorn.org/settings/#socket-binding)~

[hypercorn 支持多绑定和 dual stack](https://hypercorn.readthedocs.io/en/latest/how_to_guides/binds.html#multiple-binds)


可以使用 hypercorn 来运行 blrec，例如：`hypercorn blrec.web:app --bind 0.0.0.0:2233 --bind [::]:2233`
这样就同时绑定了 ipv4 和 ipv6 。

P.S.

- 安装 hypercorn：`pip install hypercorn`
- [blrec 的命令行参数通过环境变量指定](https://github.com/acgnhiki/blrec#%E4%BD%9C%E4%B8%BA-asgi-%E5%BA%94%E7%94%A8%E8%BF%90%E8%A1%8C)， `api_key=bili2233 hypercorn blrec.web:app --bind 0.0.0.0:2233 --bind [::]:2233`
