### ISSUE TITLE
有办法区分原画和原画PRO吗？

### ISSUE THREAD

**Issue by snfcx** [acgnhiki/blrec#131]
现在如果在主播开始前打开软件就是原画，开播了一段时间后再录制就是原画PRO了。
没有办法调整。

**Comment by CloudyEagle** [comment]
![image](https://user-images.githubusercontent.com/58777085/202740866-ff362901-4234-4c3e-b7d1-7d38d3ff2883.png)
点击直播间卡右下的三点，再点击[显示录制信息]，
若里面的画质提示的括号内有blu_ray，那么那就是原画PRO。
哔哩哔哩直播搁着恶心人呐，即使用脚本把录制链接里的
blu_ray去掉后再重定向录制，链接已是过期不存在的，
所以还是尽早打开录制软件待机吧

**Comment by sdbztpy** [comment]
如果刚开始的原画就开始录，能原画一直录到结束。后面出了二压原画再开始录，就只能录到二压原画了。
