### ISSUE TITLE
[CRITICAL]录播集体寄了

### ISSUE THREAD

**Issue by InterestingFred** [acgnhiki/blrec#132]
时间：
2022/11/22 19:28:30+08:00

现象：
录播录不上，开关按钮也没用，重启后正常

**以下摘自聊天消息记录**
22:20:19+08:00
录播没炸
22:20:26+08:00
录的就继续录的
22:20:38+08:00
没开播的就录不上了
*****************************

错误提示（邮箱）：
[mail.txt](https://github.com/acgnhiki/blrec/files/10068265/mail.txt)

日志：
（注：此日志来自环境docker-ubuntu，v1.10.0
v1.11.1也一样的）

[blrec_2022-11-11-163449-846039.log](https://github.com/acgnhiki/blrec/files/10068290/blrec_2022-11-11-163449-846039.log)
（注：13:54:06+00:00时对录播开关进行了 关 和 开 的操作）

rm -f 并重启后：
[blrec_2022-11-22-140301-222291.log](https://github.com/acgnhiki/blrec/files/10068315/blrec_2022-11-22-140301-222291.log)

**Comment by acgnhiki** [comment]
好吧，弹幕服务器 bug 把弹幕客户端干崩了。。。 
没想到弹幕服务器会出现这种 bug，下次规避下。
自动录制依赖于开播下播的弹幕，弹幕客户端寄了就只能重启 blrec 了。

**Comment by K-bai** [comment]
出现了类似情况 弹幕服务器一直报错
`[2022-11-29 03:23:22,723] [DEBUG] [danmaku_client] [22778627] Failed to send heartbeat due to: ConnectionResetError('Cannot write to closing transport')`
一直重试失败一星期没有录播（不重要

**Comment by Decretum-Wu** [comment]
我这里还有很多奇怪的现象，比如有些主播能发现开播，并获取直播流，但无法正常录制
同时整个容器似乎会一直运行到内存不足，从docker里直接吃了我宿主机10G以上的内存

可能的相关日志如下(日志皆为时间倒序，为docker日志记录)
[logs-01.txt](https://github.com/acgnhiki/blrec/files/10113975/logs-01.txt)
[logs-02.txt](https://github.com/acgnhiki/blrec/files/10113982/logs-02.txt)

其中 logs-01中是已知问题，整个弹幕客户端卡死导致需要手动重启整个容器
 2022-11-24T12:05:56.760265187Z 时间戳附近

logs-02中是新的未知问题，我这里录制了三个直播间
A直播间最早开播并正常结束，录制日志中显示的已录制大小以及录制速度等均不正常，最终只留下了319mb左右的不完整FLV录播文件
B直播间于29日14时开播，则直接未能生成录播文件，下播时提示错误
 Failed to make metadata: AssertionError(('has_video: False, video_analysed: False',))
C直播间在B直播间尚未下播时开播，其一切正常，可见录制时不断正常刷新的日志
 
 另附情况2的blrec原生日志供参考：
[blrec_2022-11-24-120611-824495.log](https://github.com/acgnhiki/blrec/files/10114012/blrec_2022-11-24-120611-824495.log)
烦请解答，感激不尽

**Comment by Decretum-Wu** [comment]
> 我这里还有很多奇怪的现象，比如有些主播能发现开播，并获取直播流，但无法正常录制 同时整个容器似乎会一直运行到内存不足，从docker里直接吃了我宿主机10G以上的内存
> 
> 可能的相关日志如下(日志皆为时间倒序，为docker日志记录) [logs-01.txt](https://github.com/acgnhiki/blrec/files/10113975/logs-01.txt) [logs-02.txt](https://github.com/acgnhiki/blrec/files/10113982/logs-02.txt)
> 
> 其中 logs-01中是已知问题，整个弹幕客户端卡死导致需要手动重启整个容器 2022-11-24T12:05:56.760265187Z 时间戳附近
> 
> logs-02中是新的未知问题，我这里录制了三个直播间 A直播间最早开播并正常结束，录制日志中显示的已录制大小以及录制速度等均不正常，最终只留下了319mb左右的不完整FLV录播文件 B直播间于29日14时开播，则直接未能生成录播文件，下播时提示错误 Failed to make metadata: AssertionError(('has_video: False, video_analysed: False',)) C直播间在B直播间尚未下播时开播，其一切正常，可见录制时不断正常刷新的日志
> 
> 另附情况2的blrec原生日志供参考： [blrec_2022-11-24-120611-824495.log](https://github.com/acgnhiki/blrec/files/10114012/blrec_2022-11-24-120611-824495.log) 烦请解答，感激不尽

刚发现问题2应该是 https://github.com/acgnhiki/blrec/issues/124 中提到的...问题1就是本issue中提到的问题，应该不需要额外确认了
