### ISSUE TITLE
现在新安装必须安装VS了吗？

### ISSUE THREAD

**Issue by threewatermeter** [acgnhiki/blrec#17]
我记得之前的版本不用使用VS的安装包安装那么多东西啊。

**Comment by acgnhiki** [comment]
不是所有 Python 包都有提供编译好的二进制库的 ┑(￣Д ￣)┍
之前的版本如果用 Python 3.8 就只需要编译 bitarray 就可以，windows-requirements.txt 用的是第三方编译的，但是用 Python 10 其实还有其它包要编译，所以还是安装编译器自己编译吧，这样以后安装其他 Python 包也方便些。。
