### ISSUE TITLE
无法设置22端口

### ISSUE THREAD

**Issue by 848244210** [acgnhiki/blrec#171]
设置22端口后无法打开后台网页，其他端口正常，查看端口无冲突。。

**Comment by Genteure** [comment]
22 在浏览器的危险端口列表里，会主动拒绝连接。
TCP 22 端口一般是用于 SSH 的。
你为啥要把管理端口设置成 22？

**Comment by 848244210** [comment]
我是低人一等的NAT王璐璐挂机宝，只有用自带的21端口，已经找到了实现浏览器访问其他端口的教程，https://zhuanlan.zhihu.com/p/383077079
该issue可以关闭了，谢谢解答

**Comment by 848244210** [comment]
自带的22

**Comment by 848244210** [comment]
已解决
