### ISSUE TITLE
添加测试cookie的功能

### ISSUE THREAD

**Issue by Sodapopoo** [acgnhiki/blrec#181]
cookie的重要性随着b站修改弹幕协议日益增加，希望能添加一个像录播姬一样测试cookie的功能

另外buvid的值只从buvid3获取，也许可以添加个提示
![9 28 找到值](https://github.com/acgnhiki/blrec/assets/82271885/7b100048-51d1-4d85-abd9-56387f4474aa)

**Comment by acgnhiki** [comment]
> cookie的重要性随着b站修改弹幕协议日益增加，希望能添加一个像录播姬一样测试cookie的功能
> 
> 另外buvid的值只从buvid3获取，也许可以添加个提示 ![9 28 找到值](https://user-images.githubusercontent.com/82271885/271313619-7b100048-51d1-4d85-abd9-56387f4474aa.png)

现在没有 buvid 值弹幕不会被屏蔽，buvid 不是必要的。

**Comment by acgnhiki** [comment]
现在有重启和退出后端程序的 api，可以看下生成的 api 文档 [http://localhost:2233/docs](http://localhost:2233/docs)，可以在这里发送请求重启。

这个重启功能在程序出现未处理异常可能有问题，所以就没添加 UI，还是推荐用 docker 或 pm2 这些来管理比较好。
