### ISSUE TITLE
增加hls流的等待时间

### ISSUE THREAD

**Issue by Sodapopoo** [acgnhiki/blrec#182]
今天一个hls only的录播8分钟的时候hls流才可用，但是我只设置了等待5分钟，于是都没有录上😥

我认为现在的等待fmp4流的选项最大时长可能不够
希望增加等待fmp4流的时长选项，以录制b站现在出现可能延迟很长时间出现的hls流

**Comment by 6Bpencle** [comment]
![image](https://github.com/acgnhiki/blrec/assets/31346958/77caf698-8565-473e-83e4-82c38558096b)
