### ISSUE TITLE
部分hls直播间无法自动开始录制

### ISSUE THREAD

**Issue by Sodapopoo** [acgnhiki/blrec#183]
能检测到开播但是直到下播都无法自动进行录制，没有报错
必须手动关闭录制按钮再打开才能进行录制，开播前打开的直播间网页也必须整个网页刷新，否则就是黑屏，检测不到开播的状态
直播流是hls only
目前在录的暂时只有这一位在 虚拟Gamer 区是这样，已经连续4天稳定出现该问题
开播之后呈现这么一个状态
![10 2 鲸鱼娘开播失败](https://github.com/acgnhiki/blrec/assets/82271885/15ea6065-784c-4cb5-ab9d-dee0dc2ea7c7)
有时候是这样，看似在录制实则没有输出文件，信息也一动不动
![10 1 BaiduShurufa_2023-10-1_20-8-37](https://github.com/acgnhiki/blrec/assets/82271885/9ac4bfe3-df04-4426-9c8f-ce669eff66ef)
控制台不打印正在录制的信息，也不产生任何文件
![10 2 鲸鱼娘不开始录制](https://github.com/acgnhiki/blrec/assets/82271885/aeee734c-14e5-412f-82ec-7bcc727b0e77)

下面附上控制台复制的信息还有日志
[控制台信息.txt](https://github.com/acgnhiki/blrec/files/12783995/default.txt)
[blrec_2023-10-02-022941-219951.log](https://github.com/acgnhiki/blrec/files/12783997/blrec_2023-10-02-022941-219951.log)

**Comment by acgnhiki** [comment]
弹幕服务器没有发送推流的命令弹幕

虽然有轮询检查，但是检测的是 flv 流。
