### ISSUE TITLE
出现Failed to get live stream url: NoStreamQualityAvailable

### ISSUE THREAD

**Issue by makesItBetter** [acgnhiki/blrec#189]
blrec是今天安装的最新版本。发现在录制虚拟gamer区时，许多主播都无法进行录制，而对于虚拟区的其它分区，比如TopStar，虚拟Singer，虚拟日常等分区都能很好的进行录制。对于无法录制的主播，测试了flv和hls格式，以及4k、蓝光、原画、超清、高清等，发现均出现Failed to get live stream url: NoStreamAvailable。

在录制虚拟gamer区时，发现都是0B：
![image](https://github.com/acgnhiki/blrec/assets/43004184/251dfd72-e295-432d-9b5f-21826acb17ea)

查看控制台：
![image](https://github.com/acgnhiki/blrec/assets/43004184/eed4843a-96c0-4f97-854c-e566eae5835d)

其它分区可以正常录制：
![image](https://github.com/acgnhiki/blrec/assets/43004184/86966424-da96-4dda-bcdc-a95a901f2810)

**Comment by makesItBetter** [comment]
我发现好像是我使用谷歌时，用了科学上网，然后没有关闭，录制虚拟gamer区就出现这个问题，关闭之后就可以了，现在好像没问题了

**Comment by ShiinaRinne** [comment]
![image](https://github.com/acgnhiki/blrec/assets/45081750/9f4e7354-803f-4253-b05f-766c530658e0)

![image](https://github.com/acgnhiki/blrec/assets/45081750/945e49f1-1366-4e1c-a6ae-eb23bf8a7913)

同样遇到这个问题，也不止发生在虚拟主播区
昨晚用docker装的一个发现了这个问题，使用了v2raya做透明代理。
但我尝试关闭代理甚至停止v2raya的容器，并重启/重装blrec的容器后，仍然没有得到解决

**Comment by makesItBetter** [comment]
> ![image](https://private-user-images.githubusercontent.com/45081750/291440751-9f4e7354-803f-4253-b05f-766c530658e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjA3MTAsIm5iZiI6MTcwMjk2MDQxMCwicGF0aCI6Ii80NTA4MTc1MC8yOTE0NDA3NTEtOWY0ZTczNTQtODAzZi00MjUzLWIwNWYtNzY2YzUzMDY1OGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA0MzMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YWI5MzczMmIxMTI0MjZkNzFiOTI3ZmE3YjRhMDhlNjRhMWUxMWE2NmJmNmI2MTdlMDc4ODk3ODY2NTliZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZI0JIxwfNZGdryKBQ8OEGq-1wC2clPAhtPFNgu0oWS4)
> 
> ![image](https://private-user-images.githubusercontent.com/45081750/291440953-945e49f1-1366-4e1c-a6ae-eb23bf8a7913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjA3MTAsIm5iZiI6MTcwMjk2MDQxMCwicGF0aCI6Ii80NTA4MTc1MC8yOTE0NDA5NTMtOTQ1ZTQ5ZjEtMTM2Ni00ZTFjLWE2YWUtZWIyM2JmOGE3OTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA0MzMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZGVjMjc1MDY1MWEzNzk5NDJhMDFhYTU4Y2RlNjk3OTI4NzhjNWJjYjdiYzkxYTU0ZDI3N2UxNzkzZDFmZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l6-Js7QwvyapW2_-oI_CDn1nJFwfTYktwzVk9O-Xg9I)
> 
> 同样遇到这个问题，也不止发生在虚拟主播区 昨晚用docker装的一个发现了这个问题，使用了v2raya做透明代理。 但我尝试关闭代理甚至停止v2raya的容器，并重启/重装blrec的容器后，仍然没有得到解决

我之前遇到这个问题是因为开启了vpn，可以访问谷歌和github，然后流量走的是国外的，在录制虚拟gamer区时出现无法录制的问题，而其它虚拟区内的其它分区可以录制，当我关闭vpn后，流量变成国内的，发现gamer区也能正常录制了。我这里的不能录制的原因应该是使用了国外流量，而且录制的是虚拟gamer区。当我开启vpn后，之前主播是gamer区，我无法录制，但是当她之后直播的分区变成其它的，我又能正常录制了，所以我这里的问题大概是b站对国外网络录制虚拟gamer区（游戏）有限制，不知道和你的问题是不是一样。你可以看看是不是港澳台或者国外服务器，录制的是不是游戏类型的分区

**Comment by ShiinaRinne** [comment]
确实，网游手游区的录不了，试了娱乐和电台区的却可以
![image](https://github.com/acgnhiki/blrec/assets/45081750/27369252-3182-4b59-ad58-3d8ca0a71eb7)

服务器是在国内上海的，我试着关掉v2raya重新安装镜像和容器也没解决
![image](https://github.com/acgnhiki/blrec/assets/45081750/342820b9-7427-4e86-b218-4cf87e4fc170)

**Comment by ShiinaRinne** [comment]
![image](https://github.com/acgnhiki/blrec/assets/45081750/1b5fb8f2-067e-41ee-8660-26f541fc9866)

又试了一个阿里的上海服务器，也有这个问题xd 
这下确实不知道咋回事了，之后有空试着调试看看

**Comment by makesItBetter** [comment]
> ![image](https://private-user-images.githubusercontent.com/45081750/291633501-1b5fb8f2-067e-41ee-8660-26f541fc9866.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDQ3NjQsIm5iZiI6MTcwMzA0NDQ2NCwicGF0aCI6Ii80NTA4MTc1MC8yOTE2MzM1MDEtMWI1ZmI4ZjItMDY3ZS00MWVlLTg2NjAtMjZmNTQxZmM5ODY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAzNTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MmRhMDMxOTM5NDkyODExYzgyMjRjMGNkMzhmODNlOGQwMDBiNWVmY2UyNjE4Y2E0YTcyODgxNTliZTRmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2GhO9vjIoJ4rWNSfyGq4e_bl-oPzPzQ16oT_5LkImVY)
> 
> 又试了一个阿里的上海服务器，也有这个问题xd 这下确实不知道咋回事了，之后有空试着调试看看

里面可以设置flv和hls两种格式的视频，你有没有试过切换hls格式的

**Comment by ShiinaRinne** [comment]
![image](https://github.com/acgnhiki/blrec/assets/45081750/67fa1d01-ac75-4bfd-9c7c-76fedf620511)
![image](https://github.com/acgnhiki/blrec/assets/45081750/272a6ae0-8a8b-412d-9a48-833da0c36f8c)
![image](https://github.com/acgnhiki/blrec/assets/45081750/37c23302-5ba3-4807-81f2-1b8e7f8ffea6)


试过，仍然是相同错误。
看这日志，即使设置是hls，但好像仍然请求了flv?

**Comment by makesItBetter** [comment]
> ![image](https://private-user-images.githubusercontent.com/45081750/291776537-67fa1d01-ac75-4bfd-9c7c-76fedf620511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTIyNTcsIm5iZiI6MTcwMzA1MTk1NywicGF0aCI6Ii80NTA4MTc1MC8yOTE3NzY1MzctNjdmYTFkMDEtYWM3NS00YmZkLTljN2MtNzZmZWRmNjIwNTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA1NTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMzBkNjQxMzFlMzJkMWI1Y2U1NjE1MmUyNzIwOTU4MTcyZTFjZDI1MTdlMjRmMzQ1N2YwMWM4MDY4NGJiMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2wLvwefGuH4z-8D45UTHTjeNR7of3m_eJj2tFK25O4) ![image](https://private-user-images.githubusercontent.com/45081750/291776549-272a6ae0-8a8b-412d-9a48-833da0c36f8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTIyNTcsIm5iZiI6MTcwMzA1MTk1NywicGF0aCI6Ii80NTA4MTc1MC8yOTE3NzY1NDktMjcyYTZhZTAtOGE4Yi00MTJkLTlhNDgtODMzZGEwYzM2ZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA1NTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMDk4ZWJkM2Y5NDJlNjc5NTFkNDFmZWQ2YzExNzg1ZTI4MWJlMDM0NDViZGQwYmJhY2EyNWZiNTc2NDBlMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KCdi-GxRZj5G_2zkxG5hyd9m_WKPWRYb25xG_IG_TDQ) ![image](https://private-user-images.githubusercontent.com/45081750/291776634-37c23302-5ba3-4807-81f2-1b8e7f8ffea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTIyNTcsIm5iZiI6MTcwMzA1MTk1NywicGF0aCI6Ii80NTA4MTc1MC8yOTE3NzY2MzQtMzdjMjMzMDItNWJhMy00ODA3LTgxZjItMWI4ZTdmOGZmZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA1NTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZGI0OTgyMzNmNzA4MzRkOGUyMjM4MDU3YWY3NGU4N2Q3ZjVlMzkyN2E3ZjAzOWMyZmNhMDNlMTQzYjRiOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4yHaKZHEce8LwXlencpkVulTruuJS2-WPCrx6kO5nZQ)
> 
> 试过，仍然是相同错误。 看这日志，即使设置是hls，但好像仍然请求了flv?

![Screenshot_20231220_135430_com huawei browser](https://github.com/acgnhiki/blrec/assets/43004184/32c8fc85-8cbe-4132-86a6-f0203424b0e4)
这里换了高清的清晰度可以录制

**Comment by ShiinaRinne** [comment]
![image](https://github.com/acgnhiki/blrec/assets/45081750/d621d2c9-5367-4bef-8c2a-fa2300019ca0)
看到你的回复我返回去看了看，发现这个直播间10分钟前居然开始录了，期间完全没有更改过任何设置，另一个没变

不过切换为高清之后另一个确实可以录了，挺好奇是什么原因
![image](https://github.com/acgnhiki/blrec/assets/45081750/d55ef345-8a45-45b0-8539-3f6f7c75b669)
