### ISSUE TITLE
1.20-beta1无法自动转换MP4

### ISSUE THREAD

**Issue by CuteCat233** [acgnhiki/blrec#190]
转换时出现：UnicodeDecodeError
![image](https://github.com/acgnhiki/blrec/assets/126493293/6b06aaf6-9a6c-46a4-8f93-2dae03359390)
![image](https://github.com/acgnhiki/blrec/assets/126493293/dcd8dca0-180e-465a-be36-ed145b0414d7)

**Comment by aliofwind** [comment]
同上

**Comment by Arukassss** [comment]
同上

**Comment by F-e-l-t** [comment]
blrec-2.0.0-beta.1\src\blrec\postprocess\ffmpeg_metadata.py
line 160
edit:
    add encoding='utf-8' for open()
after edit:
    async with aiofiles.open(playlist_path, encoding='utf-8') as file:

**Comment by CuteCat233** [comment]
> blrec-2.0.0-beta.1\src\blrec\postprocess\ffmpeg_metadata.py line 160 edit: add encoding='utf-8' for open() after edit: async with aiofiles.open(playlist_path, encoding='utf-8') as file:

已解决
