### ISSUE TITLE
v2.0.0 b2弹幕时间轴计算问题

### ISSUE THREAD

**Issue by Sodapopoo** [acgnhiki/blrec#202]
blrecv1.13 ~ v1.15标准模式弹幕文件一般比较早，延迟4 ~ 8秒为正常时间
blrecv2.0.0 beta2 版本hls流弹幕文件一般比较晚，反向延迟1 ~ 8秒为正常时间

blrecv1.13~v1.15自动分段后弹幕会重新计算，一般比较晚，反向延迟4秒为正常时间
beta版本按大小自动分段后弹幕时间计算可能会出现问题，从分段时间后几十分钟可能都会记为0
[5050-20231106-222023-玩！.beta.txt](https://github.com/acgnhiki/blrec/files/13275316/5050-20231106-222023-.beta.txt)
[5050-20231107-023536-玩！.beta.txt](https://github.com/acgnhiki/blrec/files/13275317/5050-20231107-023536-.beta.txt)

但是我测试了较短的时间自动分段，比如一两分钟，弹幕是正常的

**Comment by Jared-02** [comment]
https://github.com/acgnhiki/blrec/issues/202#issuecomment-1801062317

遇到了同样的 issue，大概定位了一下原因，问题可能出在 `_record_start_time` 变量异常飘移。
https://github.com/acgnhiki/blrec/blob/375817fb4b89309bf4903e16628d02237f71734d/src/blrec/core/danmaku_dumper.py#L312-L323
在短房间号直播间几乎可以 100% 复现

**Comment by Jared-02** [comment]
https://github.com/acgnhiki/blrec/blob/375817fb4b89309bf4903e16628d02237f71734d/src/blrec/hls/operators/segment_dumper.py#L83-L88 
问题应该出在这里，依靠分片上的序号判断时间不一定可靠，甚至可能偏移很大 @acgnhiki
