### ISSUE TITLE
转封装为mp4后码率与原flv文件不一样

### ISSUE THREAD

**Issue by lchypwx** [acgnhiki/blrec#204]
<img width="351" alt="1" src="https://github.com/acgnhiki/blrec/assets/86903706/a9d555d8-7736-43f5-af3c-9636b141b103">
左为自动转封装，右边是原始flv文件通过obs转封装后的，测试直播画面为全黑图像，这么看来使用软件的自动转封装为mp4会二压？

**Comment by lchypwx** [comment]
<img width="673" alt="截屏2023-11-25 21 42 54" src="https://github.com/acgnhiki/blrec/assets/86903706/e3ae59f5-4613-437c-a381-bf1772bb6c5d">
找到了相关代码，看起来只是删除了无意义部分，不会影响画面质量？

**Comment by Genteure** [comment]
对的。OBS CBR 会填充一堆 00000000000000000000000 把码率撑到你设置的数那么多，把录下来的文件用二进制文件编辑器打开搜 000000000 一眼就能看见。
