### ISSUE TITLE
指定保存位置后，会被自动重置为默认值

### ISSUE THREAD

**Issue by gitiray** [acgnhiki/blrec#24]
用的是最新 Docker 方式运行
目前日志、视频、配置都是放在 `/rec` 目录下的

由于一些需求，录制的视频要与配置、日志存放在不同的文件夹下，以便映射到宿主机的不同目录
视频目录是在容器内找了个空目录 `/root`，程序的配置、日志依然使用 `/rec`

结果发现，设定视频保存位置为 `/root`，当有开始录制后会自动重置为 `/rec`（可能需要重启容器才能复现）

另外，如 #23 也希望单独目录统一存放日志，允许设定日志目录

**Comment by acgnhiki** [comment]
docker 就不要改保存目录了，那是容器内的文件系统，通过修改 docker 的 -v 参数挂载到要保存录播文件的目录。
配置文件现在可以通过 blrec 的 -c 参数修改。
下个版本加个 logs 挂载目录用于保存日志文件

**Comment by acgnhiki** [comment]
命令行参数会覆盖掉设置文件的设置，所以修改会被重置，也不要通过前端改保存目录，应该改挂载参数。
下个版本支持录播文件和日志保存到不同的目录然后挂载不同的容器目录就可以了吧，像这样：  `-v ~/path/to/logs:/logs  -v ~/path/to/records:/rec`
