### ISSUE TITLE
The original stream quality (10000) is not available录制失败

### ISSUE THREAD

**Issue by hesperiso** [acgnhiki/blrec#249]
![image](https://github.com/acgnhiki/blrec/assets/29257721/8c5fca9b-d316-4bc2-be17-e645949c45ac)
录了两个多月了，第一次这样

**Comment by Karmylr** [comment]
cookie有效吗

**Comment by hesperiso** [comment]
> cookie有效吗

试过不同电脑、不同网络、不同账号、cookie也换过了

**Comment by hesperiso** [comment]
- -||||最终还是cookie问题，打扰了
