### ISSUE TITLE
录制不完整

### ISSUE THREAD

**Issue by JYWXJ327** [acgnhiki/blrec#266]
![捕获](https://github.com/acgnhiki/blrec/assets/112244957/b02e7d25-81a1-492f-ae7c-d678f4699cf4)
如上图所示，开始时间与结束时间是一个小时十分左右，但是录制的文件只有一小时，这是什么原因？
![捕获1](https://github.com/acgnhiki/blrec/assets/112244957/71ac9edb-72f3-42f4-b6cf-4c08e5789ef9)

**Comment by maolvv** [comment]
cookie配置了么，记得以前好像cookie无效的时候会出现录制不及时开始的情况

**Comment by JYWXJ327** [comment]
> cookie配置了么，记得以前好像cookie无效的时候会出现录制不及时开始的情况

把无痕模式下面的cookie放在设置里面，这个cookie能维持多久

**Comment by JYWXJ327** [comment]
> cookie配置了么，记得以前好像cookie无效的时候会出现录制不及时开始的情况

把无痕模式下面的cookie放在设置里面，这个cookie能维持多久，需要一直把无痕页面开着吗

**Comment by maolvv** [comment]
> > cookie配置了么，记得以前好像cookie无效的时候会出现录制不及时开始的情况
> 
> 把无痕模式下面的cookie放在设置里面，这个cookie能维持多久，需要一直把无痕页面开着吗

无痕页是可以关的，但不太清楚cookie什么时候会过期，目前在cookie的配置页面那边，用测试功能结果是正常的么？然后录播那边少掉的时段是哪片呢？如果不是开头少了，那可能会是其他问题

**Comment by JYWXJ327** [comment]
> > > cookie配置了么，记得以前好像cookie无效的时候会出现录制不及时开始的情况
> > 
> > 
> > 把无痕模式下面的cookie放在设置里面，这个cookie能维持多久，需要一直把无痕页面开着吗
> 
> 无痕页是可以关的，但不太清楚cookie什么时候会过期，目前在cookie的配置页面那边，用测试功能结果是正常的么？然后录播那边少掉的时段是哪片呢？如果不是开头少了，那可能会是其他问题

cookie测试结果是正常的，录播刚开始的时候也是准时开始的，然后过了一段时间之后就开始中断了接着就直接结束了。然后问一下就是舰长专属的直播间的话，把无痕模式下面的cookie放在设置里面就可以了吗

**Comment by maolvv** [comment]
> > > > cookie配置了么，记得以前好像cookie无效的时候会出现录制不及时开始的情况
> > > 
> > > 
> > > 把无痕模式下面的cookie放在设置里面，这个cookie能维持多久，需要一直把无痕页面开着吗
> > 
> > 
> > 无痕页是可以关的，但不太清楚cookie什么时候会过期，目前在cookie的配置页面那边，用测试功能结果是正常的么？然后录播那边少掉的时段是哪片呢？如果不是开头少了，那可能会是其他问题
> 
> cookie测试结果是正常的，录播刚开始的时候也是准时开始的，然后过了一段时间之后就开始中断了接着就直接结束了。然后问一下就是舰长专属的直播间的话，把无痕模式下面的cookie放在设置里面就可以了吗

按说是舰长账号的cookie放那边就行了，我没遇到过舰限的直播不太确定。中间断开的话，会不会是网络的问题？

**Comment by JYWXJ327** [comment]
> > > > > cookie配置了么，记得以前好像cookie无效的时候会出现录制不及时开始的情况
> > > > 
> > > > 
> > > > 把无痕模式下面的cookie放在设置里面，这个cookie能维持多久，需要一直把无痕页面开着吗
> > > 
> > > 
> > > 无痕页是可以关的，但不太清楚cookie什么时候会过期，目前在cookie的配置页面那边，用测试功能结果是正常的么？然后录播那边少掉的时段是哪片呢？如果不是开头少了，那可能会是其他问题
> > 
> > 
> > cookie测试结果是正常的，录播刚开始的时候也是准时开始的，然后过了一段时间之后就开始中断了接着就直接结束了。然后问一下就是舰长专属的直播间的话，把无痕模式下面的cookie放在设置里面就可以了吗
> 
> 按说是舰长账号的cookie放那边就行了，我没遇到过舰限的直播不太确定。中间断开的话，会不会是网络的问题？

好的 谢谢啦
