### ISSUE TITLE
添加十位数的直播间报错

### ISSUE THREAD

**Issue by Arukassss** [acgnhiki/blrec#267]
https://live.bilibili.com/1820907263
![QQ截图20240520104452](https://github.com/acgnhiki/blrec/assets/89686441/f5bac00e-d8f2-4127-8696-7900df048e1c)

**Comment by CuteCat233** [comment]
\blrec-v2.0.0-beta.3-win64\python\Lib\site-packages\blrec\setting\models.py
这个文件里面找到318行的99999999，往后面多加俩9就行
