### ISSUE TITLE
主播推流网络问题导致自动拼合生成文件错误 / 如何禁用网络波动时自动拼合文件

### ISSUE THREAD

**Issue by Small-Dianer** [acgnhiki/blrec#270]
环境：
Unraid下Docker部署

问题出现在：
1.FMP4直播流的直播间
_2.设置了时长自动分段（2小时分段）_ （可能与该问题无关，我设置了而已。）

案例：
主播在该次分段后的10分钟时推流出现问题（表现为直播间卡顿/反复循环最后几秒内容），不久后马上推流跟上。

录制的视频文件会出现：
1.使用播放器播放/导入到视频编辑软件都显示只有10分钟左右时长，但是文件大小约等于2个小时的正常文件时长
2.到主播卡顿前的内容正常，后续~2小时设置的分段点内容以极快的速度闪过（可以理解成2小时的内容加速到了2秒内播放完毕）
3.软件检测不到错误，在默认设置下，源文件（m4s和m3u8文件）转换成MP4后会被删除

样本：
较大，如需样本我上传后贴连接到此

希望解决：
1.拼合生成正常的MP4文件
2.如果无法达到1，则在检测到主播推流出问题的时候，主动断开连接重新录制（生成新的文件）而不是自动拼合成一个不正常的问题

**Comment by obsession9** [comment]
可以通过mkvmerge工具手动将m4s文件转为mkv文件，几乎都能正常播放。
当然仍有极小的概率转换出来的mkv也会有这个问题。

另外对于录制出来的flv文件也会极小概率出现这种情况。

**Comment by Small-Dianer** [comment]
已尝试通过mkvmerge工具手动将m4s转换为mkv，可以正常播放
ffmpeg将mkv copy为mp4后也正常。
感谢！
