### ISSUE TITLE
关于 邮件通知的一个小问题

### ISSUE THREAD

**Issue by po-lan** [acgnhiki/blrec#35]
我使用的Outlook
![image](https://user-images.githubusercontent.com/42771836/161217843-09a9a66e-d80b-4b78-8710-267fce49237f.png)
会报错
![image](https://user-images.githubusercontent.com/42771836/161218404-f64e1840-7db1-4d0a-adb2-9dd0453029a1.png)
这是outlook上的信息
![image](https://user-images.githubusercontent.com/42771836/161218443-88ebd454-e095-4546-a76f-24aa312e1a12.png)

我怀疑是因为 stmp的加密方式不同的原因
      加密方法: STARTTLS

发送，接受都是使用的 是E5全局的子账号

**Comment by po-lan** [comment]
![image](https://user-images.githubusercontent.com/42771836/161225350-e28890e0-935d-405d-8bde-bd77db1796ba.png)

**Comment by acgnhiki** [comment]
现在不支持  STARTTLS 加密方法，下个版本加上。

**Comment by po-lan** [comment]
好的，期待下个版本了
