### ISSUE TITLE
选择HLS录制出现的问题

### ISSUE THREAD

**Issue by Arukassss** [acgnhiki/blrec#39]
主播开播的时候有大概10秒左右的无数据，之后间歇性的网络波动
![3](https://user-images.githubusercontent.com/89686441/162602313-3f81a3da-3a16-4c35-987a-e525bf625fc1.png)
在任务页面显示数据也不再刷新就卡住了，停止录制本地也无文件
![2](https://user-images.githubusercontent.com/89686441/162602264-6e6c8c4c-5d76-4045-b015-75186db3314c.png)
![5](https://user-images.githubusercontent.com/89686441/162602449-e7c5707d-9acf-4d4b-bc16-120791f78e19.png)
切换回flv就正常录制了
![4](https://user-images.githubusercontent.com/89686441/162602429-5ed54082-bf6b-43ce-a420-7c8f20d428b6.png)

运行环境是docker，blrec版本为1.6.0

**Comment by Arukas0122** [comment]
测试环境：srt推流   2K 44.1KHZ   2K 48.0KHZ
输出的文件目前没发现输出文件进度条与绿屏问题，均正常，但是在录制过程中任务页面的显示依旧有问题，和上述的一样卡住不显示，录制结束之后却有文件

**Comment by acgnhiki** [comment]
主播开播后要等推流，不同的直播条件下推流延迟可能不一样，有的甚至超过了  1 分钟，只有推流了后解析了数据才会更新数据及显示。如果是刚开播那是正常的，如果是录制一段时间后停止更新那就是程序出问题了。因为 HLS 是一个一个小片段，所以下载和录制就会出现间歇性波动。

**Comment by Arukassss** [comment]
不是刚开播的，例如下图，截图时间为19点13分，已经开播了十多分钟，页面看的数据依旧是有问题的
![1](https://user-images.githubusercontent.com/89686441/162615395-f0b4bfa7-1768-4cad-90c2-043894825001.png)
文件详情和本地文件如下
![2](https://user-images.githubusercontent.com/89686441/162615465-7db758e6-ec81-44c6-bafa-3ed6b0a7721a.png)
![3](https://user-images.githubusercontent.com/89686441/162615469-b46ef9ca-b31b-41f1-9660-8d9a3a53b34f.png)

**Comment by Arukassss** [comment]
重新启动之后发现流主机去到了d1--cn-gotcha208.bilivideo.com，数据又正常了
![4](https://user-images.githubusercontent.com/89686441/162615805-2a1e9abc-6e5d-4804-b2ab-6b31c4ffcdf3.png)

**Comment by Arukassss** [comment]
个别主播即使连接的流主机正常，但是依旧存在有网络但是无数据写入的情况，本地无文件但是网络却有使用的，此时直播页面已经有画面几分钟了
![5](https://user-images.githubusercontent.com/89686441/162616020-45551ea0-88bb-494f-aab3-37532687a8c8.png)

**Comment by acgnhiki** [comment]
HLS 目前还是实验性的，录制某些直播间可能有问题。 HLS 主要是相对于 FLV 不容易中断，可以大概率保持不录到二压流，如果主播推流码率比较低不会被二压还是用 FLV 格式比较好。
