### ISSUE TITLE
关于保存封面

### ISSUE THREAD

**Issue by gitiray** [acgnhiki/blrec#42]
目前的逻辑是在每次保存文件时储存封面，如果对文件大小设定了限制（分割），会导致每个分段都生成一次封面，通常都是重复的图片。虽说不占太多空间，但做了无用功，还要额外清理，有些多余。

我觉得只生成一次封面就好了。
比如可以在开始录制时就生成，或是多个分段只在第一次生成。

**Comment by acgnhiki** [comment]
保存封面这个功能之前是为了某个自动化工具的需求添加的，每个文件都保存一次封面并且和录播文件使用相同的文件名主要是方便自动化工具能容易找到封面。

有些主播开播后才改封面，这样在开始录制就保存封面有可能保存的是上次直播的。

如果改了可能会影响到那个自动化工具，暂时还是不改了，之后再考虑加个封面保存策略什么的。

**Comment by gitiray** [comment]
懂了，那就还是提供选项吧
