### ISSUE TITLE
短暂断网后的无限刷

### ISSUE THREAD

**Issue by po-lan** [acgnhiki/blrec#43]
![image](https://user-images.githubusercontent.com/42771836/163233069-c613eaac-6428-4707-bcf3-c3c6785fa85d.png)
上边的信息已经刷了好几分钟了 
断网后录制（时间）可以继续 但是网络不走 但是他在不停的刷
![image](https://user-images.githubusercontent.com/42771836/163233334-4ee4c7da-51f1-4e26-a5a4-ba0799bd273c.png)
![image](https://user-images.githubusercontent.com/42771836/163233421-f9351eb5-e3c5-4f18-8c00-b0ccf1354615.png)
很快就会把日志文件写道10MB
这是第一个日志 第二个都是相同的内容重复报错
[blrec_2022-04-13-200554-946393.log](https://github.com/acgnhiki/blrec/files/8483346/blrec_2022-04-13-200554-946393.log)

这是我用powershell写的一个run.sp1，没用解决之前提过的缩放闪退的问题 也就这么用着了
与 cmd体验基本相同
`$env:path=".\python;.\ffmpeg\bin;" + $env:path

# 绕过系统代理
$env:no_proxy='*'

# 服务器主机和端口绑定，去掉注释并按照自己的情况修改。
$thost="0.0.0.0"
$port=2233

$env:DEFAULT_LOG_DIR = "E:\lbj\OneDrive - luohui1\log"
$env:DEFAULT_OUT_DIR = "E:\lbj\OneDrive - luohui1\LB"

&python -m blrec -c settings.toml --open --host $thost --port $port

pause`

**Comment by acgnhiki** [comment]
这个好像是 CDN 的问题，flv 的请求返回了 html 文件（从文件开头 `<ht` 猜测）？

看了下我录着测试的日志，也出现了多个直播间同时断掉，然后发送错误的数据，看着也像是服务器返回了 html 网页~
```log
[2022-04-15 00:15:45,822] [WARNING] [flv_stream_recorder] [22603245] FlvStreamCorruptedError("FlvHeaderError('<!D')")
```

 `<!DOCTYPE html>`

**Comment by po-lan** [comment]
> 这个好像是 CDN 的问题，flv 的请求返回了 html 文件（从文件开头 `<ht` 猜测）？
> 
> 看了下我录着测试的日志，也出现了多个直播间同时断掉，然后发送错误的数据，看着也像是服务器返回了 html 网页~
> 
> ```
> [2022-04-15 00:15:45,822] [WARNING] [flv_stream_recorder] [22603245] FlvStreamCorruptedError("FlvHeaderError('<!D')")
> ```
> 
> `<!DOCTYPE html>`

d当我手动断掉后录制 可以正常进行

**Comment by acgnhiki** [comment]
> > 这个好像是 CDN 的问题，flv 的请求返回了 html 文件（从文件开头 `<ht` 猜测）？
> > 看了下我录着测试的日志，也出现了多个直播间同时断掉，然后发送错误的数据，看着也像是服务器返回了 html 网页~
> > ```
> > [2022-04-15 00:15:45,822] [WARNING] [flv_stream_recorder] [22603245] FlvStreamCorruptedError("FlvHeaderError('<!D')")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `<!DOCTYPE html>`
> 
> d当我手动断掉后录制 可以正常进行

我的是换了几次 url 就恢复了，看日志你那个一直在换 url 还是发送了错误的数据，可能连的 CDN 比较差。

**Comment by po-lan** [comment]
> 我的是换了几次 url 就恢复了，看日志你那个一直在换 url 还是发送了错误的数据，可能连的 CDN 比较差。

好的

**Comment by acgnhiki** [comment]
> > 我的是换了几次 url 就恢复了，看日志你那个一直在换 url 还是发送了错误的数据，可能连的 CDN 比较差。
> 
> 好的 我先换一下我的CDN 如果可以的话 能写着程序里做一个限制 吗

CDN 是服务器自动根据你的 ip 所在地自动分配的，似乎不能随意修改的吧？

**Comment by po-lan** [comment]
> > > 我的是换了几次 url 就恢复了，看日志你那个一直在换 url 还是发送了错误的数据，可能连的 CDN 比较差。
> > 
> > 
> > 好的 我先换一下我的CDN 如果可以的话 能写着程序里做一个限制 吗
> 
> CDN 是服务器自动根据你的 ip 所在地自动分配的，似乎不能随意修改的吧？
看差了，看成DNS了

**Comment by acgnhiki** [comment]
> > > > 我的是换了几次 url 就恢复了，看日志你那个一直在换 url 还是发送了错误的数据，可能连的 CDN 比较差。
> > > 
> > > 
> > > 好的 我先换一下我的CDN 如果可以的话 能写着程序里做一个限制 吗
> > 
> > 
> > CDN 是服务器自动根据你的 ip 所在地自动分配的，似乎不能随意修改的吧？
> > 看差了，看成DNS了

不过可以考虑服务器发送错误数据就换备用线路，备用线路好像是不同的 CDN。

**Comment by po-lan** [comment]
> 

好的，这个应该需要你更新新的版本了

**Comment by acgnhiki** [comment]
> > 
> 
> 好的，这个应该需要你更新新的版本了

今天准备把几个 bug 修下就发个 v1.6.1

**Comment by po-lan** [comment]
> > > 
> > 
> > 
> > 好的，这个应该需要你更新新的版本了
> 
> 今天准备把几个 bug 修下就发个 v1.6.1

好，感谢大佬
