### ISSUE TITLE
由于 Chrome 对 ServiceWorker 响应 BasicAuth 存在 BUG，请求增加登陆认证功能

### ISSUE THREAD

**Issue by gitiray** [acgnhiki/blrec#44]
程序部署在VPS，迫于无认证直接暴露在公网不安全，为了不给您负担、没有发功能请求，直接拿 [Caddy](https://caddyserver.com/) 反代容器，启用 [basicauth](https://caddyserver.com/docs/caddyfile/directives/basicauth)，顺便套了一个 Cloudflare CDN，如此认证凑合够用。

确保网络环境正常，使用电脑和安卓 Chrome，打开 https://blrec.example.com/ ，无法访问（偶尔能），浏览器提示 `net::ERR_FAILED`，控制台报错

```
The FetchEvent for "https://blrec.example.com/" resulted in a network error response: the promise was rejected.
ngsw-worker.js:74 Uncaught (in promise) Error: Response not Ok (fetchAndCacheOnce): request for https://blrec.example.com/index.html returned response 401 
    at PrefetchAssetGroup.fetchAndCacheOnce (https://blrec.example.com/ngsw-worker.js:74:131)
    at async PrefetchAssetGroup.handleFetch (https://blrec.example.com/ngsw-worker.js:64:11)
    at async https://blrec.example.com/ngsw-worker.js:139:116
    at async AppVersion.handleFetch (https://blrec.example.com/ngsw-worker.js:139:42)
    at async Driver.handleFetch (https://blrec.example.com/ngsw-worker.js:237:97)
```

一番搜索找到 https://bugs.chromium.org/p/chromium/issues/detail?id=623464 ，和我到情况很像（其实我也偶尔提示401，但更多时候是 `net::ERR_FAILED`）。

升级最新版 PC Chrome 100，刚开始正常，后来又无法访问，控制台报错

```
The FetchEvent for "https://blrec.example.com/tasks" resulted in a network error response: the promise was rejected.
Promise.then (async)
onFetch @ ngsw-worker.js:210
(anonymous) @ ngsw-worker.js:203
ngsw-worker.js:74 Uncaught (in promise) Error: Response not Ok (fetchAndCacheOnce): request for https://blrec.example.com/index.html returned response 401 
    at PrefetchAssetGroup.fetchAndCacheOnce (ngsw-worker.js:74:131)
    at async PrefetchAssetGroup.handleFetch (ngsw-worker.js:64:11)
    at async ngsw-worker.js:139:116
    at async AppVersion.handleFetch (ngsw-worker.js:139:42)
    at async Driver.handleFetch (ngsw-worker.js:237:97)
```

这符合 https://bugs.chromium.org/p/chromium/issues/detail?id=623464#c21 提到的：可能某些情况下还是会有问题。

对于手机，尝试升级安装Webview 结果直接闪退，浏览器都无法使用，有点尴尬。

---

综上，考虑到 Chrome 依然没完全解决此问题、修复进度十分缓慢，而安卓设备更新 Webview 则容易出现兼容问题。
可能还是需要向您提出功能请求：**增加一个简单的登陆认证页面**。

**Comment by acgnhiki** [comment]
blrec 现在有 api-key 安全认证: https://swagger.io/docs/specification/authentication/api-keys/

考虑下加上 api-key？毕竟不是网站，个人使用我觉得 api-key 认证简单够用。
目前 api-key 有一定的安全限制，3 次尝试内 api-key 正确客户端 ip 会自动加入白名单，3 次错误后则 ip 会被加入黑名单，黑名后请求直接 403，黑名单和白名单数以及同时尝试连接的 ip 数量限制各为 100，黑名单或白名单到达限制后不再接受除了白名单内的其它 ip 。只有重启才会清空黑名单和白名单。

api-key 认证的代码： https://github.com/acgnhiki/blrec/blob/master/src/blrec/web/security.py

**Comment by gitiray** [comment]
在现有基础上改造当然是最好的啦

目前api-key好像是自动生成的吧，意思是改成环境变量自己设置么？
然后在访问网页到时候应该会弹窗让输api_key？之前偶尔遇到过这个弹窗

**Comment by acgnhiki** [comment]
api key 不会自动生成，要通过命令行参数指定，可以使用数字和字母，长度限制为最短 8 最长 80，例如： `blrec  --api-key bili2233` 。
第一次访问网页会弹窗要求输 api key ，输入的 api key 会保存在浏览器的 local storage 里，下次使用同一浏览器就不用再输入了。

**Comment by gitiray** [comment]
重新看了更新日志，原来从1.4版本开始是支持api-key的

是我疏忽了，还在这琢磨BasicAuth😅

感谢耐心解答，已经用上，效果不错
