### ISSUE TITLE
弹幕记录一个都没开，为何还会生成一个XML

### ISSUE THREAD

**Issue by CloudyEagle** [acgnhiki/blrec#45]
使用blrec没有很长时间，使用经验不多。
请问弹幕记录一个都没开，为何还会生成一个XML
![Snipaste_2022-04-17_19-24-54](https://user-images.githubusercontent.com/58777085/163713135-f0a48fa9-9d95-4ae7-b30a-0935131f6ce6.png)
![Snipaste_2022-04-17_19-27-06](https://user-images.githubusercontent.com/58777085/163713141-0bea1ee1-6dc5-4e56-824d-e73ae3ba4c69.png)

**Comment by acgnhiki** [comment]
现在是不能选择是否要录制弹幕的，保存用户发送的弹幕是默认行为，选项是和礼物相关的弹幕。
