### ISSUE TITLE
录制被迫中断，录到二压原画流

### ISSUE THREAD

**Issue by CloudyEagle** [acgnhiki/blrec#46]
![2022-04-17_203215](https://user-images.githubusercontent.com/58777085/163715201-3039d15b-658e-45f2-8e4e-e7c9092bf8f8.png)
![Snipaste_2022-04-17_20-28-32](https://user-images.githubusercontent.com/58777085/163715288-5392eea5-78dc-4b9a-aee3-847cf146359a.png)
我没开添加元数据录制会有两个文件，前一个是未二压的，后一个应该是录到二压流了；
网页端的显示录制信息里多了个bluray，视频信息和音频信息码率也无法正常显示了。

**Comment by CloudyEagle** [comment]
我现在还用着1.6..0，请问使用最近更新的1.6.1版本可以避免这种情况呀

**Comment by acgnhiki** [comment]
flv 比较容易断，断了会录制到二压流现在是无法避免的。
录制 hls 流有比较大概率不会录制到二压流，不过录制 hls 目前还是实验性的，录制有些直播间会出错（主要是 ffmpeg 遇到流数据错误就会出错导致录制停止）。
