### ISSUE TITLE
控制台可能还是有些bug的

### ISSUE THREAD

**Issue by po-lan** [acgnhiki/blrec#47]
![image](https://user-images.githubusercontent.com/42771836/163749435-9d26f8a8-ebce-46dd-b177-0adcd4f62d99.png)
控制台显示还在录制，但是录制已经结束了，速度和体积也不在变
![image](https://user-images.githubusercontent.com/42771836/163749527-f9086384-eb74-425b-a503-fee99fbebad1.png)
网页上是正常的
但是点进来也是录制的状态
![image](https://user-images.githubusercontent.com/42771836/163749581-160f27fd-4d8a-4653-870f-6c2845c42d40.png)
![image](https://user-images.githubusercontent.com/42771836/163749594-ea7ca387-887c-4f08-bc04-6b3ac275bf60.png)
录制方式flv
一直报错这个
![image](https://user-images.githubusercontent.com/42771836/163749641-aa7684d9-6d60-4993-abae-450b5e0c1f32.png)
[blrec_2022-04-16-161232-009429.log](https://github.com/acgnhiki/blrec/files/8503255/blrec_2022-04-16-161232-009429.log)

**Comment by po-lan** [comment]
手动关闭这个房间的录制也无法解决
[blrec_2022-04-16-161232-009429.log](https://github.com/acgnhiki/blrec/files/8503265/blrec_2022-04-16-161232-009429.log)

**Comment by po-lan** [comment]
退出后也会报错
![image](https://user-images.githubusercontent.com/42771836/163750062-bb9ea1ba-c93c-4cfb-9ac3-18fc844d06c9.png)

**Comment by po-lan** [comment]
![image](https://user-images.githubusercontent.com/42771836/163750485-6dd5af4c-9a3b-4325-9a0f-baebfb391462.png)
我用任务管理器退出后也无法转mp4

**Comment by acgnhiki** [comment]
Even Loop 既然崩了。。。 估计是 Windows asyncio 有些兼容性问题

**Comment by po-lan** [comment]
> 

emmm
虽然说之前的版本没用遇到过
今天又遇到过别的bug
![image](https://user-images.githubusercontent.com/42771836/164050299-80bd9174-6b1c-41a8-adea-de8d72bcc804.png)
![image](https://user-images.githubusercontent.com/42771836/164050328-eb3c6653-c24b-4700-898f-b5496c2b8e3b.png)
[blrec_2022-04-18-113030-836172.log](https://github.com/acgnhiki/blrec/files/8514750/blrec_2022-04-18-113030-836172.log)

**Comment by po-lan** [comment]
> > 退出后也会报错 ![image](https://user-images.githubusercontent.com/42771836/163750062-bb9ea1ba-c93c-4cfb-9ac3-18fc844d06c9.png)
> 
> 这是按了 ctrl + c 吗？

是的

**Comment by acgnhiki** [comment]
> > > 退出后也会报错 ![image](https://user-images.githubusercontent.com/42771836/163750062-bb9ea1ba-c93c-4cfb-9ac3-18fc844d06c9.png)
> > 
> > 
> > 这是按了 ctrl + c 吗？
> 
> 是的

Window  有时按 ctrl + c 都没反应

> ![image](https://user-images.githubusercontent.com/42771836/163749435-9d26f8a8-ebce-46dd-b177-0adcd4f62d99.png) 控制台显示还在录制，但是录制已经结束了，速度和体积也不在变 ![image](https://user-images.githubusercontent.com/42771836/163749527-f9086384-eb74-425b-a503-fee99fbebad1.png) 网页上是正常的 但是点进来也是录制的状态 ![image](https://user-images.githubusercontent.com/42771836/163749581-160f27fd-4d8a-4653-870f-6c2845c42d40.png) ![image](https://user-images.githubusercontent.com/42771836/163749594-ea7ca387-887c-4f08-bc04-6b3ac275bf60.png) 录制方式flv 一直报错这个 ![image](https://user-images.githubusercontent.com/42771836/163749641-aa7684d9-6d60-4993-abae-450b5e0c1f32.png) [blrec_2022-04-16-161232-009429.log](https://github.com/acgnhiki/blrec/files/8503255/blrec_2022-04-16-161232-009429.log)

直播软件崩了等情况没有正常停止直播，还处于直播状态却没有在推流就会这样一直尝试继续录制。

**Comment by po-lan** [comment]
> 还处于直播状态却没有在推流就会这样一直尝试继续录制

不过在网页里 已经不会显示 ![image](https://user-images.githubusercontent.com/42771836/164051673-01234768-35cf-4922-8ec9-b37a62bff673.png)这个东西了
但是点击进去
![image](https://user-images.githubusercontent.com/42771836/164051732-06596ec0-3a95-4ea9-a192-48e0c81b143a.png)
![image](https://user-images.githubusercontent.com/42771836/164051754-52538063-d800-4c8f-b74c-5ae4ec06018b.png)
就是这样的

**Comment by po-lan** [comment]
![image](https://user-images.githubusercontent.com/42771836/164364447-0ec00efb-6b82-4c06-b515-928bcf6079fa.png)
