### ISSUE TITLE
同一局域网下，手机无法访问

### ISSUE THREAD

**Issue by CloudyEagle** [acgnhiki/blrec#48]
![Screenshot_20220414_160201](https://user-images.githubusercontent.com/58777085/163751262-d1f81a0a-076a-48eb-98f3-b68ce1e26852.jpg)
![Snipaste_2022-04-18_11-39-22](https://user-images.githubusercontent.com/58777085/163751279-09d7a5ca-f03d-4da7-a888-d23d74d72f6b.png)
我把防火墙关了以及添加出入站规则也没用，其中出入站规则里UDP有改用过TCP，也没有成功，请问哪里还需要设置修改
![Snipaste_2022-04-18_11-38-19](https://user-images.githubusercontent.com/58777085/163751375-c4b23a39-8280-4ba1-9dad-dc2f4711fc84.png)
![Snipaste_2022-04-18_11-37-54](https://user-images.githubusercontent.com/58777085/163751410-4a64ef2e-3f4e-44fe-b258-f843af966702.png)
![Snipaste_2022-04-18_11-37-30](https://user-images.githubusercontent.com/58777085/163751423-33984d8d-dfc6-4ef9-909f-f30f6167a635.png)

**Comment by acgnhiki** [comment]
你是用的免安装版吧？
把 `run.bat` 这一行的注释去掉：https://github.com/acgnhiki/blrec/blob/master/run.bat#L14

**Comment by CloudyEagle** [comment]
![Snipaste_2022-04-19_07-30-35](https://user-images.githubusercontent.com/58777085/163892937-e908ea7b-32f9-4679-97cb-580afe834167.png)
![Screenshot_20220419_072756_com microsoft emmx](https://user-images.githubusercontent.com/58777085/163892990-b6d972ec-ff63-41d4-a16a-3e726c302ef5.png)
总算是折腾出来了，如果可以跟去qBittorrent那样修改个port后，
不管用localhost或者127.0.0.1还是用局域网内的本机IP都可以访问就好了
![Snipaste_2022-04-19_07-28-50](https://user-images.githubusercontent.com/58777085/163893192-a6b91f03-65a2-48f8-bcee-469f17c3b64d.png)

**Comment by acgnhiki** [comment]
你把 `set host=192.168.1.30`  改成  `set host=0.0.0.0` ，这样本机和和局域网内的设备就都可以访问。

**Comment by CloudyEagle** [comment]
感谢，受教了。
