### ISSUE TITLE
PushDeer添加PushKey失败

### ISSUE THREAD

**Issue by threewatermeter** [acgnhiki/blrec#56]
![微信截图_20220506141328](https://user-images.githubusercontent.com/9511059/167077059-31864f4e-4df9-483c-b623-63b111aa4efd.png)

**Comment by sihuan** [comment]
请问你的 pushkey 在 `PUD` 与第一个字母 `T` 之间的数字 uid 有几位？
现在对 pushkey 的正则验证是按 `[a-zA-Z\d]{41}` 进行的（也就是字母或数字共 41 位），通过阅读 pushkey 的源码知，pushkey 的格式为`PUD`+_uid_+`T`+32位随机字符串，我不确定你的 uid 有多少位，如果不是 5 位的话就说明现在的正则匹配规则有点问题，需要改动一下正则匹配。

**Comment by acgnhiki** [comment]
> 请问你的 pushkey 在 `PUD` 与第一个字母 `T` 之间的数字 uid 有几位？ 现在对 pushkey 的正则验证是按 `[a-zA-Z\d]{41}` 进行的（也就是字母或数字共 41 位），通过阅读 pushkey 的源码知，pushkey 的格式为`PUD`+_uid_+`T`+32位随机字符串，我不确定你的 uid 有多少位，如果不是 5 位的话就说明现在的正则匹配规则有点问题，需要改动一下正则匹配。

https://github.com/easychen/pushdeer/blob/ff21e69382669b3b1707e744268367897724ca31/api/app/Http/Controllers/PushDeerKeyController.php#L32

uid 位数不知，但应该不是固定的。

**Comment by sihuan** [comment]
~修的好快，失去混 pr 的机会~
