### ISSUE TITLE
希望pushdeer推送的时候能增加直播间链接

### ISSUE THREAD

**Issue by sakurayun** [acgnhiki/blrec#64]
就像这样：
`[直播间链接](https://live.bilibili.com/xxxx)`
pushdeer支持markdown来着（（

**Comment by acgnhiki** [comment]
用 Liquid 整个消息模板 🤔  让大家自由发挥 🙂

**Comment by acgnhiki** [comment]
ee066403629c693fdcee0c13c01a1ec679f8bc96  已经在默认消息模板中加了直播间链接
