### ISSUE TITLE
弹幕录制的sc数值有错误

### ISSUE THREAD

**Issue by mylolis** [acgnhiki/blrec#66]
30元的sc录制下来变成30000了，看了下xml里的数值是错的
price="30000" time="60"
停留时间是正确的，但price数值多了三个零
而在原始弹幕数据json中是正确的
"price": 30,

**Comment by acgnhiki** [comment]
#18  为了方便按价格过滤礼物才改成这样的

**Comment by mylolis** [comment]
这样是能统一价格过滤礼物了，但要怎么样才能让付费礼物的价格正常呢，是否可以只将免费礼物除1000呢？

**Comment by acgnhiki** [comment]
现在付费礼物统一的单位是金瓜子    免费礼物单位是银瓜子，除1000 那要用什么单位？

**Comment by mylolis** [comment]
我的意思是免费礼物除1000也能实现过滤作用，同时付费礼物也能以正确的价格显示

**Comment by mylolis** [comment]
> 现在付费礼物统一的单位是金瓜子 免费礼物单位是银瓜子，除1000 那要用什么单位？

或者需要怎么样可以让sc价格显示正常？

**Comment by mylolis** [comment]
知道怎么改了，感谢作者大佬

**Comment by akiaki1996** [comment]
> 知道怎么改了，感谢作者大佬

想问下是怎么改的？

**Comment by mylolis** [comment]
> > 知道怎么改了，感谢作者大佬
> 
> 想问下是怎么改的？

src/blrec/core/danmaku_dumper.py这个文件里最下面_make_super_chat_record这一项有个price=msg.price * msg.rate，根据你的需要把 * msg.rate删掉就行了，这个是改sc的，改舰长的话就_make_guard_buy_record里改price=msg.price // 1000

**Comment by akiaki1996** [comment]
> > > 知道怎么改了，感谢作者大佬
> > 
> > 
> > 想问下是怎么改的？
> 
> src/blrec/core/danmaku_dumper.py这个文件里最下面_make_super_chat_record这一项有个price=msg.price * msg.rate，根据你的需要把 * msg.rate删掉就行了，这个是改sc的，改舰长的话就_make_guard_buy_record里改price=msg.price // 1000

好的，谢谢您！
