### ISSUE TITLE
设备的BUG通知最好能自定义个设备名称啥的

### ISSUE THREAD

**Issue by KNaiFen** [acgnhiki/blrec#67]
设备多了我现在收到报错信息我都不知道是哪台机子，得一台台看过去

**Comment by acgnhiki** [comment]
#64  之后会考虑加 Liquid 消息模板，引入环境变量，支持自定义消息。

**Comment by acgnhiki** [comment]
ee066403629c693fdcee0c13c01a1ec679f8bc96  已支持自定义通知消息，设备名称啥的可以自己通过环境变量添加然后在消息模板中引用。
