### ISSUE TITLE
关于增加断网检测的建议

### ISSUE THREAD

**Issue by dalaofy** [acgnhiki/blrec#7]
bilibili live recorder 录播工具的优点是网络波动自动拼接，但是现在同时带来了一个问题，录制方在录制过程中本地网络长期断网录制状态无法结束，是否应当增设本地网络检测，如无法接受直播间数据后尝试链接B站主页百度主页等页面进行本地网络检测，如返回404状态确定本地断网后一定时间内生成原有文件，不易造成文件明显漏录，建议断网切割时长加入菜单中，可供用户选择断网等候时间。

**Comment by acgnhiki** [comment]
如果网络真的这么拉跨应该尝试改善网络提高录播质量而不是试图让一个录制工具去适应这种网络……
