### ISSUE TITLE
错误的时间戳记录及没有成功生成的metadata-comment

### ISSUE THREAD

**Issue by InterestingFred** [acgnhiki/blrec#70]
## 使用版本：1.7.1 windows免安装版、非服务器运行

# 问题1：一次录播的长度不到2:10:00的时长但是断流时间戳却标记在大于2:30:00的位置，同时播放flv时进度条无法超过1:07:56
【这个主播那一天播了三次，此问题出现在第二次直播，与第一次直播有数个小时的间隔】
【这个主播在此次下播后立马使用手机进行了直播，此时injecting还未结束】
![图片](https://user-images.githubusercontent.com/106480847/170876283-c414b15c-69c2-4cbd-a6a4-8dfdd86f6c9c.png)

# 问题2：在另一次的录播中，在injecting之后，没有看到comment字段
![图片](https://user-images.githubusercontent.com/106480847/170876457-0a867b1d-0079-4461-9125-3ee81d91153e.png)
![图片](https://user-images.githubusercontent.com/106480847/170876474-16713fbe-9f78-40f1-8ce3-8324d3c7403e.png)

# 附上期间的日志文件：
出现问题的是5/28的15点多开始的这一场（问题1）以及5/29的16.54开始的这一场（问题2，这一场刚开录的时候使用的网络状况不太好，但也算是录上了，直到直播已经开始40分钟后手动调整后网络恢复正常）
[blrec_2022-05-22-110156-089575.log](https://github.com/acgnhiki/blrec/files/8793608/blrec_2022-05-22-110156-089575.log)

**Comment by InterestingFred** [comment]
[blrec_2022-05-22-110156-089575.log](https://github.com/acgnhiki/blrec/files/8793623/blrec_2022-05-22-110156-089575.log)

**Comment by InterestingFred** [comment]
补充：问题1中是拖动进度条无法超过1:07:56 播放以及转成MP4之后没问题的

**Comment by acgnhiki** [comment]
第一个问题是中间有一个时间戳为 0 的 ScriptTag 导致时间戳计算错误了，重构的代码 a460c1e9be56e0fe8fc4eca91056587f08aee3e5 已处理了这个问题。

第二个问题应该是拼接记录比较多导致 Comment 太长 ffmpeg 解析出错了，VLC 或 Mediainfo 应该可以看到有这个值。

**Comment by InterestingFred** [comment]
![图片](https://user-images.githubusercontent.com/106480847/171012939-fecba4a6-031b-465d-96d0-9ecaff24945b.png)
VLC3.0.16，好像也没有诶，是我的打开方式不对吗

**Comment by acgnhiki** [comment]
Mediainfo 也没有吗？

**Comment by InterestingFred** [comment]
## 好消息，树状图模式没有，但是文本模式有，好诶
![图片](https://user-images.githubusercontent.com/106480847/171017294-98f8c820-a46c-43e0-80c0-4dd2e0fda747.png)
![图片](https://user-images.githubusercontent.com/106480847/171017660-59f1d6ea-3ae8-48af-a361-5ecd6d419b7b.png)

00000BE3A   StringLength2:                        7 (0x0007)
00000BE3C   StringData2:                          Comment
00000BE43   Type:                                 2 (0x02)
00000BE44   Value_Size:                           1446 (0x05A6)
00000BE46   Value:                                B站直播录像 / 主播：芷小菡 / 标题：继续做饼干 / 分区：电台 - 聊天电台 / 房间号：1011107 / 开播时间：2022-05-29 16:52:28+08:00 / 流主机: d1--cn-gotcha04.bilivideo.com / 流格式：flv / 流画质：原画 (10000) / 录制程序：blrec v1.7.1 https://github.com/acgnhiki/blrec /  / 流中断拼接详情 / 时间戳：00:00:33.266, 无缝拼接：是 / 时间戳：00:15:25.499, 无缝拼接：是 / 时间戳：00:15:35.161, 无缝拼接：是 / 时间戳：00:15:36.370, 无缝拼接：是 / 时间戳：00:24:48.286, 无缝拼接：是 / 时间戳：00:25:05.310, 无缝拼接：是 / 时间戳：00:37:43.085, 无缝拼接：是 / 时间戳：00:39:02.885, 无缝拼接：是 / 时间戳：00:39:18.706, 无缝拼接：否 / 时间戳：00:41:39.245, 无缝拼接：是 / 时间戳：03:06:52.659, 无缝拼接：是 / 时间戳：04:08:30.098, 无缝拼接：否 / 时间戳：04:09:11.041, 无缝拼接：否 / 时间戳：04:26:03.190, 无缝拼接：是 / 时间戳：04:28:40.350, 无缝拼接：否 / 时间戳：04:28:43.295, 无缝拼接：是 / 时间戳：04:28:49.880, 无缝拼接：否 / 时间戳：04:31:57.865, 无缝拼接：是 / 时间戳：04:32:06.697, 无缝拼接：是 / 时间戳：04:33:45.959, 无缝拼接：否 / 时间戳：04:51:10.312, 无缝拼接：否 / 时间戳：04:56:08.400, 无缝拼接：是 / 时间戳：05:32:17.394, 无缝拼接：否 / 时间戳：05:37:03.009, 无缝拼接：否 / 时间戳：05:38:30.964, 无缝拼接：否
00000C3EC  description (346 bytes)

# 好诶，可以close了
