### ISSUE TITLE
究极恶性BUG，程序甚至无法启动

### ISSUE THREAD

**Issue by KNaiFen** [acgnhiki/blrec#71]
blrec现在启动了就这样，一直卡着无法添加任务
![UJ42 %%N DC1YTGRB@1PBZN](https://user-images.githubusercontent.com/53338804/170908607-72f882b6-3668-4430-84f7-a9ced73bb419.png)
日志里边显示一直在重复操作
![D14B$1A(0AW~A2WP7{112IB](https://user-images.githubusercontent.com/53338804/170908671-816ea190-dafa-46af-a05e-d2f2dd408559.png)
webui都无法连接上去了
![`OTD$}_$S4~U} {(M`IW)QL](https://user-images.githubusercontent.com/53338804/170908699-53b0e1b6-1463-433d-a402-ea724b8dbc56.png)
之前一直能用，唯一的区别就是昨晚我给这台win的机子配置了openssh，以便我远控用，但是刚刚把openssh卸载了，也还是没变化，重启机子了也不行

**Comment by KNaiFen** [comment]
[blrec_2022-05-30-104747-273985.log](https://github.com/acgnhiki/blrec/files/8795067/blrec_2022-05-30-104747-273985.log)

**Comment by acgnhiki** [comment]
emmm... 你这看着怎么像是被 ban 了    
日志没连接的异常信息，不知道是什么问题~
你重新运行下，一分钟后（连接弹幕服务器会重试一分钟）看有什么异常。

**Comment by KNaiFen** [comment]
我已经重试了一天了，启动时间绝对不止一分钟，几个小时都有，而且同个机子下的录播姬是正常录制的

**Comment by acgnhiki** [comment]
emmm...  有没有试过 docker 版？

**Comment by KNaiFen** [comment]
这是我刚刚启动的日志，成功载入了三个直播间，第四个就一直连不上了
[blrec_2022-05-30-221045-765298.log](https://github.com/acgnhiki/blrec/files/8799004/blrec_2022-05-30-221045-765298.log)

**Comment by KNaiFen** [comment]
我下次试试绿色版

**Comment by acgnhiki** [comment]
短时间内请求数过多，你的 ip 被风控了。。。（试过多开录制 几百个直播间就会这样， 同一 ip 下网页或客户端访问也会出问题。。。）

**Comment by KNaiFen** [comment]
呃，录播姬为啥就没事= =，请求的接口不一样吗

**Comment by acgnhiki** [comment]
blrec 优先使用 android api

**Comment by acgnhiki** [comment]
啊 B 的风控好像是过段时间就会恢复的， 如果有其它软件在不断发请求的话那估计恢复不了。我记得录播姬会轮询直播状态，录的直播间比较多的话，可能会有影响。

**Comment by KNaiFen** [comment]
如果可以的话。。。。加个录播姬那边的接口吧。。。。录播姬常年上百个都没问题

**Comment by acgnhiki** [comment]
551d8abab2af9e5ad0783d9e3b62aec0610b07a2
现在改成优先使用 web 接口了，web 接口出错才会切换为 android 接口。

发布为测试版，安装要指定版本号：`pipx install blrec==1.8.0a0`

**Comment by threewatermeter** [comment]
> [551d8ab](https://github.com/acgnhiki/blrec/commit/551d8abab2af9e5ad0783d9e3b62aec0610b07a2) 现在改成优先使用 web 接口了，web 接口出错才会切换为 android 接口。
> 
> 发布为测试版，安装要指定版本号：`pipx install blrec==1.8.0a0`

现在pipx安装还需要安装vs吗

**Comment by KNaiFen** [comment]
> [51d8ab](https://github.com/acgnhiki/blrec/commit/551d8abab2af9e5ad0783d9e3b62aec0610b07a2) 现在51d8ab接口会变成优先使用，web接口会变成android android接口。
> 
> 发布为测试版，安装要指定版本号：`pipx install blrec==1.8.0a0`

好好好好好

**Comment by KNaiFen** [comment]
换了18a1之后能正常启动加入直播间了
