### ISSUE TITLE
使用HLS流录制时出现弹幕与视频不同步

### ISSUE THREAD

**Issue by mylolis** [acgnhiki/blrec#73]
似乎是由于hls流出现较晚，而弹幕先于视频开始录制，导致弹幕与视频有几秒的时间差

**Comment by mylolis** [comment]
> 视频和弹幕并不是完全同步的，推流有一定延迟而且不同主播也不一样（通常是十几秒左右），所以通常录播画面会比弹幕延迟十几秒左右，看起来就是弹幕比视频先出现了十几秒左右。
> 
> 开始录制直播流才开始保存弹幕的且弹幕的时间是相对于视频开始录制的时间计算的，流出现的延迟应该不会影响视频和弹幕的同步。
> 
> ```
> 
>   开播		                        开始录制直播流
>   开始接收弹幕		                开始保存弹幕（在这个时间点以及之前发送的弹幕的时间戳都为 0）
> 	
>      <--------------- 延迟 ------------->
> ___|_____________________________________|_____________________________________
>  
> ```

当使用flv流录制时，这个弹幕延迟就相对较低。所以觉得会不会是由于hls流相较于flv更晚出现（延迟更高）才出现这种情况。并且弹幕延迟的时间差不多等于log里live start和等待fmp4流出现开始接受数据的时间差

**Comment by acgnhiki** [comment]
> > 视频和弹幕并不是完全同步的，推流有一定延迟而且不同主播也不一样（通常是十几秒左右），所以通常录播画面会比弹幕延迟十几秒左右，看起来就是弹幕比视频先出现了十几秒左右。
> > 开始录制直播流才开始保存弹幕的且弹幕的时间是相对于视频开始录制的时间计算的，流出现的延迟应该不会影响视频和弹幕的同步。
> > ```
> > 
> >   开播		                        开始录制直播流
> >   开始接收弹幕		                开始保存弹幕（在这个时间点以及之前发送的弹幕的时间戳都为 0）
> > 	
> >      <--------------- 延迟 ------------->
> > ___|_____________________________________|_____________________________________
> >  
> > ```
> 
> 当使用flv流录制时，这个弹幕延迟就相对较低。所以觉得会不会是由于hls流相较于flv更晚出现（延迟更高）才出现这种情况。并且弹幕延迟的时间差不多等于log里live start和等待fmp4流出现开始接受数据的时间差

好像是的，开播时间到流可用的时间差不多就是弹幕与视频的延迟，估计加上这个延迟弹幕和视频就接近同步了。

**Comment by acgnhiki** [comment]
不同主播的延迟差异有些大，的确不能在录制的时候给弹幕加延迟，有的加了反而错了，还是记录下流可用时的时间戳然后后期自己调比较靠谱。

**Comment by acgnhiki** [comment]
Commen 加了几个时间记录作为参考


```
开播时间：2022-06-18 14:00:44+08:00
开始推流时间: 2022-06-18 14:00:46+08:00
HLS流可用时间: 2022-06-18 14:00:48+08:00
开始录制时间: 2022-06-18 14:00:51+08:00
```

不是自动开始录制或没有接收到相应弹幕 `开始推流时间` 为 `N/A`
录的不是 HLS 流或 `开始推流时间` 为 `N/A` 那 `HLS流可用时间` 也是  `N/A`
