### ISSUE TITLE
录制后无法转码

### ISSUE THREAD

**Issue by qiaokeli151** [acgnhiki/blrec#74]
在其中一个直播间中发现，设阀为5G一个视频，到了4.99G就录制终端
![问题](https://user-images.githubusercontent.com/106548447/171396069-cd5a7787-b89e-4c89-9b0c-08bbb70c468a.png)
![1](https://user-images.githubusercontent.com/106548447/171396108-329b5033-d775-4cc9-8eff-295c3a28fa5a.png)
[blrec_2022-05-31-220810-283851.log](https://github.com/acgnhiki/blrec/files/8813672/blrec_2022-05-31-220810-283851.log)

**Comment by InterestingFred** [comment]
https://github.com/acgnhiki/blrec/blob/master/FAQ.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BD%95%E6%92%AD%E6%96%87%E4%BB%B6%E7%9A%84%E6%97%B6%E9%95%BF%E5%B0%8F%E4%BA%8E%E7%9B%B4%E6%92%AD%E6%8C%81%E7%BB%AD%E6%97%B6%E9%97%B4
似乎可以回答4.99这部分问题

**Comment by qiaokeli151** [comment]
> [https://github.com/acgnhiki/blrec/blob/master/FAQ.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BD%95%E6%92%AD %E6%96%87%E4%BB%B6%E7%9A%84%E6%97%B6%E9%95%BF%E5%B0%8F%E4%BA%8E%E7%9B%B4%E6 %92%AD%E6%8C%81%E7%BB%AD%E6%97%B6%E9%97%B4](https://github.com/acgnhiki/blrec/blob/master/FAQ.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BD%95%E6%92%AD%E6%96%87%E4%BB%B6%E7%9A%84%E6%97%B6%E9%95%BF%E5%B0%8F%E4%BA%8E%E7%9B%B4%E6%92%AD%E6%8C%81%E7%BB%AD%E6%97%B6%E9%97%B4) 看起来可以回答4.99这部分问题

但是其他人的转码很正常

**Comment by acgnhiki** [comment]
7e4f0620a2418f8b2302a5e79f65902a9735aa01

导致没转码的 bug 修了 ，安装：`pipx install blrec==1.8.0a1`

现在没有成功进行后处理就会显示状态为录制中断，这样显示可能不是很好，以后再改改。
