### ISSUE TITLE
日志里出了我看不懂的error

### ISSUE THREAD

**Issue by InterestingFred** [acgnhiki/blrec#75]
第一次见出了个ERROR，版本180a0
![图片](https://user-images.githubusercontent.com/106480847/171611845-8e127a48-cc3f-496d-b1b4-45531e3f02dc.png)
我也不知道是啥问题，就当样本发上来吧
没什么问题的话可以直接close
附上log
[blrec_2022-06-01-024956-707827.log](https://github.com/acgnhiki/blrec/files/8823015/blrec_2022-06-01-024956-707827.log)

**Comment by InterestingFred** [comment]
补充：是windows免安装的180a0
当然现在已经在用180a1了

**Comment by acgnhiki** [comment]
获取主播用户信息超时了，看日志重试了很多次才连接上弹幕客户端，不是网络差可能就是被风控了。

**Comment by InterestingFred** [comment]
其实是笔记本换WiFi()，经常一堆debug然后一个reconnected的warning，但是error还是第一次见

**Comment by acgnhiki** [comment]
> 其实是笔记本换WiFi()，经常一堆debug然后一个reconnected的warning，但是error还是第一次见

那个请求重试超过 1 分钟就放弃重试了，切网络如果没能在 1 分钟内恢复连接就会出现那个异常。
