### ISSUE TITLE
绿色版修改启动脚本中的ip和端口后，启动时无法自动打开对应的web

### ISSUE THREAD

**Issue by threewatermeter** [acgnhiki/blrec#79]
修改启动脚本中的ip后，自动弹出的依然是localhost:2233

**Comment by acgnhiki** [comment]
一般监听的地址是 localhost 或 0.0.0.0，localhost 都可以访问，自动打开的地址就写死为 localhost 了。

如果改了其它 localhost 不能访问的 ip，那么还是把 --open 参数去掉，手动打开浏览器访问吧。
