### ISSUE TITLE
可否增加录制完成写入关键帧索引的开关

### ISSUE THREAD

**Issue by threewatermeter** [acgnhiki/blrec#8]
使用别的自动上传录播至b站的软件,如果录制完成就开始写入元数据,会导致上传报错,可否增加不写入元数据的选项

**Comment by acgnhiki** [comment]
没更新元数据就不算录制完成，等录制的文件完成了再上传，用 webhook 监听录播文件完成事件。

**Comment by acgnhiki** [comment]
e36dedce74430eff5d07faa169d566ef6fcbfe5d
