### ISSUE TITLE
文件名含直播间标题时应进行非法字符替换或转写

### ISSUE THREAD

**Issue by bybybybyb** [acgnhiki/blrec#83]
要是哪天主播真的想不开在直播间标题里加入了没办法用作文件名的字符的话可能会造成文件无法写入磁盘。

具体字符可参照 https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

**Comment by acgnhiki** [comment]
直播间标题、主播名、分区名中不能用于文件名的字符会被去除

https://github.com/acgnhiki/blrec/blob/master/src/blrec/core/path_provider.py#L32-L35

https://github.com/acgnhiki/blrec/blob/master/src/blrec/path/helpers.py#L43-L44

**Comment by bybybybyb** [comment]
多谢！是我读代码不细心（
