### ISSUE TITLE
当主播出现网络问题导致流中断时，弹幕却依然在录制

### ISSUE THREAD

**Issue by mylolis** [acgnhiki/blrec#84]
由于网络或电脑问题主播方流中断一段时间后恢复推流触发了无缝拼接：否，由于弹幕在流中断期间并没有停止录制，导致弹幕和视频的时间轴对不上，多出了流中断期间的弹幕。即画面跳过了一部分，而弹幕依然在继续。
解决方法要么在主播流中断期间不录制弹幕，或者主播流中断后分割文件
不知道哪种更好

**Comment by acgnhiki** [comment]
不是不得不分都不考虑  `分割文件` 
不能因流中断就  `不录制弹幕`  漏掉那些弹幕 

之前有考虑过这个问题，就是还鸽着：
流录制中断就暂停保存弹幕（弹幕还会继续接收）
流录制恢复后把在流中断期间接收到的所有弹幕时间戳都调整为流录制中断开始的时间后保存
调整弹幕的时间差继续保存弹幕
