### ISSUE TITLE
启动失败？

### ISSUE THREAD

**Issue by CloudyEagle** [acgnhiki/blrec#86]
![image](https://user-images.githubusercontent.com/58777085/177042089-d0889e20-5671-46f7-a068-4bee69975d0a.png)
我在自用的Windows Server 2008 R2 SP1里尝试使用Win64绿色版，提示缺少运行的dll。
是我系统装的太旧了导致的吗？现已经趋向于稳固使用中了，装了不少我要用的软件了。
还是你们已经开始不支持Windows 7及其服务器版本嘞

**Comment by acgnhiki** [comment]
绿色版用的是 Python 3.10，这系统太老了，Python 3.10 不支持。

https://www.python.org/downloads/windows/ 

`Note that Python 3.10.0 cannot be used on Windows 7 or earlier.`

**Comment by CloudyEagle** [comment]
所以你们是不会考虑用旧的python版本以兼容Win7了吗？
个人不太喜欢用Win10系统以及对应的Server 2016以上的系统当服务器跑。

**Comment by acgnhiki** [comment]
免安装版用的是可嵌入版的 Python , 最新的 Windows 10 或 Windows Server 2016+ 应该不会缺 C 运行时可以做到 ”免安装“；而 Windwos 7 或 Windows Server 2012 要安装 KB2533623 系统更新而且可能还会缺 C 运行时做不到”免安装“，所以免安装只能支持 Windows 10+ 或 Windows Server 2016+。

https://docs.python.org/3.8/using/windows.html#the-embeddable-package

```
Note The embedded distribution does not include the Microsoft C Runtime and it is the responsibility of the application installer to provide this. The runtime may have already been installed on a user’s system previously or automatically via Windows Update, and can be detected by finding ucrtbase.dll in the system directory.
```

```
Note When running on Windows 7, Python 3.8 requires the KB2533623 update to be installed. The embeddable distribution does not detect this update, and may fail at runtime. Later versions of Windows include this update.
```

---

这个项目对 Python 版本的最低要求是 3.8，Python 3.8 是支持 Windows 7 或 Windows Server 2012+ 的，你可以自己安装 Python 3.8 再用 pip 或 pipx 安装 blrec（可能要自己安装缺少的系统更新或 C 运行时）

**Comment by CloudyEagle** [comment]
![image](https://user-images.githubusercontent.com/58777085/202398455-0b1068d3-4f95-4e96-97f2-608777b17c53.png)
在自己搭建的录制服务器，系统Windows Server 2008 R2 SP1，上成功跑起，感谢作者的指导。
