### ISSUE TITLE
能否支持自动上传功能？

### ISSUE THREAD

**Issue by ZoidbergPi** [acgnhiki/blrec#95]

**Comment by acgnhiki** [comment]
不支持

**Comment by Georgebillion** [comment]
> _No description provided._

上传B站GITHUB上有现成的代码，自己搜一下部署一下应该不难吧，而且有webhook情况下自行自动化部署也不难吧？
其他站点的请自行GITHUB搜一下就星，这块本来也不属于blrec的本质工作，留了webhook本来就是为了自行自动化，扩展性做准备的。

**Comment by ZoidbergPi** [comment]
> 

好的谢谢
