### ISSUE TITLE
希望能指定配置文件地址，方便脚本自动更新

### ISSUE THREAD

**Issue by happytommyl** [acgnhiki/blrec#97]
最好是能将配置文件放置在用户配置文件夹内，ie.
`%LocalAppData%\blrec`

并将Apikey等配置移到配置文件中

**Comment by acgnhiki** [comment]
设置文件的位置可以通过命令行参数  `-c` 指定

不推荐直接修改设置文件，如果 blrec 处于运行中修改是不会生效的。

api key 放配置文件可能不安全，写个 .sh 或 .bat 文件把 api key 写里面会比较好些。

**Comment by MaiReo** [comment]
设置文件这东西，通常是搞一个http api，专门用来更新设置文件。
隔壁好像搞了这玩意。bug甚多。不建议搞这东西
