### ISSUE TITLE
[问题咨询]文件名包含injecting的是什么文件

### ISSUE THREAD

**Issue by MaiReo** [acgnhiki/blrec#99]
录制视频保存的目录我没有给删除权限，有两个flv文件，两个文件大小看起来差不多，一个文件名是模板.flv，一个是模板- injecting.flv，哪个可以删除呢？ 能不能禁用injecting？ oss会产生额外的存储费用（删除的文件不足30天按30天计费）

**Comment by acgnhiki** [comment]
带 injecting 后缀的 flv 文件加了关键帧索引 , 完成后会替换没关键帧索引的源文件。 关掉 `flv 添加元数据` 就可以禁用加关键帧索引（ `injecting`）

**Comment by threewatermeter** [comment]
有个问题是有时候会遇到带 injecting 后缀的文件没删除,不知道是没替换成功还是替换完没删除成功

**Comment by acgnhiki** [comment]
> 有个问题是有时候会遇到带 injecting 后缀的文件没删除,不知道是没替换成功还是替换完没删除成功

如果日志里有 `Successfully injected metadata for 录播文件路径` 就是替换成功了，不然就是失败了。

替换文件用的 `os.replace` 是一个原子操作，应该不会出现 `替换完没删除成功` 的情况。
